### PR TITLE
Do not match String.format(Locale, String, Object...)

### PR DESCRIPTION
**Pull request by timtebeek**
Partial fix for #122

### CODE REVIEW

**Comment by timtebeek** [comment]
There's some possibly unrelated compilation errors that suddenly pop up:
```
e: /home/runner/work/rewrite-migrate-java/rewrite-migrate-java/src/test/kotlin/org/openrewrite/java/migrate/apache/commons/io/ApacheIOUtilsUseExplicitCharsetTest.kt: (32, 13): Type mismatch: inferred type is JavaParser! but Parser.Builder! was expected
e: /home/runner/work/rewrite-migrate-java/rewrite-migrate-java/src/test/kotlin/org/openrewrite/java/migrate/guava/NoGuavaImmutableListOfTest.kt: (335, 16): Type mismatch: inferred type is RecipeRun! but List<Result> was expected
e: /home/runner/work/rewrite-migrate-java/rewrite-migrate-java/src/test/kotlin/org/openrewrite/java/migrate/guava/NoGuavaImmutableMapOfTest.kt: (372, 16): Type mismatch: inferred type is RecipeRun! but List<Result> was expected
e: /home/runner/work/rewrite-migrate-java/rewrite-migrate-java/src/test/kotlin/org/openrewrite/java/migrate/guava/NoGuavaImmutableSetOfTest.kt: (335, 16): Type mismatch: inferred type is RecipeRun! but List<Result> was expected
e: /home/runner/work/rewrite-migrate-java/rewrite-migrate-java/src/test/kotlin/org/openrewrite/java/migrate/lang/StringFormattedTest.kt: (28, 21): Type mismatch: inferred type is JavaParser! but Parser.Builder! was expected
```

**Comment by pway99** [comment]
Thanks Tim,  Looks like you found some rewrite 7.29.0 breaking changes, I've fixed them on the main branch

**Comment by timtebeek** [comment]
Thanks for the quick fix! Now I can check the test failures early tomorrow morning. :)

**Comment by pway99** [comment]
Sounds good thanks!  :)

**Comment by pway99** [comment]
Hi Tim,  I added a Java 17 JavaVersion applicability test and attempted to solve the formatting issues by copying the original argument prefixes to the transformed method invocation.   If you don't mind have a look at the `doNotChangeWhitespaceWithNewlinesAndComments` and `doNotChangeWhitespaceWithNewlines` tests since I changed them a bit also.  Going to close this PR since the commits have been merged to the main branch.

6e59237954fd3f3a5efe3d2b2b3aab2ad01a0bc2

**Comment by timtebeek** [comment]
Ah awesome, thanks so much for clearing it up! And good to see a new set of tricks I can apply to other recipes. Coming up with the new test cases was a fun exercise, aided by my inadvertently adversarial colleagues just doing what they do. :)

**Comment by pway99** [comment]
Hi Tim!  I just learned about `Applicability#and(TreeVisitor<?, P>... vs)` and updated the StringFormatted single source applicability test; also I added an `Assertions#version(SourceSpecs, int)` and was able to remove the SourceSpec cast from the tests.  Thanks for your help on this one :)

**Pull request closed without merging**
