### PR TITLE
Revert adding SerialVersionUID

### PR DESCRIPTION
**Pull request by melloware**
@DidierLoiseau @timtebeek has convinced me this is bad change and leave only the `@Serial` in

### CODE REVIEW

**Comment by DidierLoiseau** [comment]
For reference, this follows a discussion in #560. Thanks @melloware for you reactivity.

@timtebeek, I don’t think it’s possible to downgrade `rewrite-migrate-java` when running the Maven plugin from the command-line without declaring the plugin in the pom, right? Would it be possible to make a new release of the plugin (with the updated bom) once this is fixed?

**Comment by timtebeek** [comment]
Thanks both! It's definitely possible to override just one recipe module. I'll push a patch release of this one

**Comment by DidierLoiseau** [comment]
@timtebeek 

> It's definitely possible to override just one recipe module.

without configuring the plugin in the pom?

**Comment by timtebeek** [comment]
Absolutely! You can do so by passing in `-Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:2.26.1`
https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html#recipeartifactcoordinates

**Comment by timtebeek** [comment]
Hmm that's unfortunate; not quite sure how Maven merges conflicting plugin dependencies; perhaps there's ordering there too? So would `-Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:2.26.1,you.library:second:1.0.1` work?

**Pull request merged**
