### PR TITLE
jacoco upgrade now includes arbitrary jacoco deps (eg agent), always …

### PR DESCRIPTION
**Pull request by nmck257**
…sends to highest patch version, and happens in the java 6 recipe (and therefore runs at every java upgrade)

## What's changed?

see title

## What's your motivation?

- apps using offline instrumentation may also have the jacoco agent in their dependencies
- pretty much any java upgrade might require a jacoco upgrade, depending on the initial version, and the current recipes only touched jacoco at certain versions

## Anything in particular you'd like reviewers to focus on?

the test file has a reference to "latest jacoco version" which would need to be maintained over time for the tests to pass; I forget if we have a tidier pattern for cases like this

### Checklist
- [X] I've added unit tests to cover both positive and negative cases
- [X] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [X] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by nmck257** [comment]
whoops, fixed - thanks!

**Review by timtebeek — APPROVED** [review]
Thanks a lot! Cleaner indeed to have it all in one place. I didn't know JaCoCo is so strongly backwards compatible to older Java version; that sure makes this easier.

**Comment by nmck257** [comment]
Sure thing, thanks for adjusting the test case to avoid the hardcoded version!

**Comment by timtebeek** [comment]
> Sure thing, thanks for adjusting the test case to avoid the hardcoded version!

Yeah just saving future me some time down the road. :) Didn't want to trouble you for it.

**Pull request merged**
