### PR TITLE
Update maven-compiler-plugin in pluginManagement

### PR DESCRIPTION
**Pull request by timtebeek**
Following on from
- https://github.com/openrewrite/rewrite/pull/3707

Fixes https://github.com/openrewrite/rewrite-migrate-java/issues/353

### CODE REVIEW

**Comment by timtebeek** [comment]
@ammachado figured pick this up after your change to the XPathMatcher, but somehow this isn't working just yet. Do you spot anything I might have missed?

**Comment by ammachado** [comment]
I pushed my changes to #359.

**Comment by timtebeek** [comment]
Yes thanks, seems like we arrived at the same fix & test, but for some reason the `//` isn't working for me yet. Not sure why 😕

**Comment by timtebeek** [comment]
Thanks for the work on XPathMatcher @ammachado ! Really nice to just add those double slashes here for an improved recipe.

**Pull request merged**
