### PR TITLE
Polish recipe for migration JakartaEE Authz/Authn

### LINKED ISSUE #166: Polish recipe for migration JakartaEE Authz/Authn
After resolving issue #160, some changes were added[1], and I think it's necessary to polish a particular aspect of these changes. For recipe `JavaxAuthorizationMigrationToJakartaAuthorization`, the Maven Add dependency step was added and IMHO, there's a certain inaccuracy in it. 

Current one:
```
- org.openrewrite.maven.AddDependency:
      groupId: jakarta.authorization
      artifactId: jakarta.authorization-api
      version: 2.x
      onlyIfUsing: jakarta.security.jacc..*
```

Proposed one:
```
- org.openrewrite.maven.AddDependency:
      groupId: jakarta.authorization
      artifactId: jakarta.authorization-api
      version: 2.x
      onlyIfUsing: javax.security.jacc..*
```

The prop `onlyIfUsing` was changed from `jakarta.security.jacc..*` to `javax.security.jacc..*`. IMHO, it makes more sense in this context as we add the new dependency when there's some reference to the old package in a codebase. 
When in the codebase, the new reference to package `jakarta.security.jacc..*` is used, we assume the new dependency is already included in the project due to the fact it would not be possible to compile the project.

WDYT? cc: @tkvangorder

[1] https://github.com/openrewrite/rewrite-migrate-java/commit/c06ccc96ceb11077858b4a3487fe4c74037771f6

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #166

@tkvangorder Hello, could you please check it? Thank you :))

More info in the attached issue.

### CODE REVIEW

**Comment by mabartos** [comment]
@timtebeek Thanks for your response! 

I wasn't sure if it was necessary also to update test cases for each particular recipe. I thought the present test cases are more "type-based" centric, such as some general ones for `org.openrewrite.maven.AddDependency:`, etc.

However, yep, I'll try to make a test case for the Jakarta Authz recipe.

**Comment by timtebeek** [comment]
Thanks for the quick response and offer to write such a test; let me know if you need any help!

**Comment by sambsnyd** [comment]
Do we maybe need both? Like an earlier version of the jakarta dependency would _also_ need to be updated to 2.x

**Comment by sambsnyd** [comment]
I'm going to add an UpgradeDependencyVersion as well to address the situation where an earlier version of jakarta.authorization-api may already be present:
```yaml
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: jakarta.authorization
      artifactId: jakarta.authorization-api
      newVersion: 2.x
```

**Comment by sambsnyd** [comment]
Thanks for the contribution @mabartos !

**Pull request merged**
