### PR TITLE
Fix Jakarta EE 10 migration - fix reference, fix Faces annotations

### PR DESCRIPTION
**Pull request by OndroMih**
## What's changed?

Fixes to the Jakarta EE 10 recipe introduced in https://github.com/openrewrite/rewrite-migrate-java/pull/350:

* Fixes reference to the FacesManagedBeansRemoved recipe
* Fixes some annotations in the Faces Managed Beans transformation - references to old name were to non-deprecated variants and only jakarta prefix was changed
* Adds transformations for Faces Managed Beans annotattions in their jakarta variants (otherwise migration from Jakarta EE 9 to 10 ignores them)

## What's your motivation?

To fix the recipe to work when migrating from Jakarta EE 9 to 10, not only migrating Jakarta EE 8 to 10.

### Checklist
- [X] I've added unit tests to cover both positive and negative cases - not applicable, already covered by tests
- [X] I've added the license header to any new files through `./gradlew licenseFormat` - not applicable
- [X] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Review by ranuradh — APPROVED** [review]
looks good to me..

**Review by ranuradh — APPROVED** [review]

**Comment by timtebeek** [comment]
Thanks for the suggested fixes here @OndroMih ; I do notice a new test failure where we used the old imports. 
```
FacesManagedBeansRemovedTest > updateFacesManagedBean() FAILED
    org.opentest4j.AssertionFailedError: [Unexpected result in "ApplicationBean2.java":
    diff --git a/ApplicationBean2.java b/ApplicationBean2.java
    index a567e38..2305f2b 100644
    --- a/ApplicationBean2.java
    +++ b/ApplicationBean2.java
    @@ -1,10 +1,11 @@ 
    -import jakarta.enterprise.context.ApplicationScoped;
     import jakarta.enterprise.context.Dependent;
    -import jakarta.enterprise.context.RequestScoped;
    -import jakarta.enterprise.context.SessionScoped;
     import jakarta.faces.annotation.ManagedProperty;
     import jakarta.faces.view.ViewScoped;
 
    +import javax.enterprise.context.ApplicationScoped;
    +import javax.enterprise.context.RequestScoped;
    +import javax.enterprise.context.SessionScoped;
    +
     @ApplicationScoped
     @RequestScoped
     @SessionScoped
    ] 
    expected: 
      "import jakarta.enterprise.context.ApplicationScoped;
      import jakarta.enterprise.context.Dependent;
      import jakarta.enterprise.context.RequestScoped;
      import jakarta.enterprise.context.SessionScoped;
      import jakarta.faces.annotation.ManagedProperty;
      import jakarta.faces.view.ViewScoped;
  
      @ApplicationScoped
      @RequestScoped
      @SessionScoped
      @ManagedProperty
      @Dependent
      @ViewScoped
      public class ApplicationBean2 {
      }"
     but was: 
      "import jakarta.enterprise.context.Dependent;
      import jakarta.faces.annotation.ManagedProperty;
      import jakarta.faces.view.ViewScoped;
  
      import javax.enterprise.context.ApplicationScoped;
      import javax.enterprise.context.RequestScoped;
      import javax.enterprise.context.SessionScoped;
  
      @ApplicationScoped
      @RequestScoped
      @SessionScoped
      @ManagedProperty
      @Dependent
      @ViewScoped
      public class ApplicationBean2 {
      }"
```

Would it be possible for you to update that test to use the new source classes? In there's then missing type information on the inputs perhaps @ranuradh can help resolve those.

**Comment by ranuradh** [comment]
@timtebeek I tried in my environment If the test I added an extra line 
```
@Test
    void updateFacesManagedBean() {
        rewriteRun(
          //language=java
          java(
            """
            import javax.enterprise.context.ApplicationScoped;
            import javax.enterprise.context.RequestScoped;
            import javax.enterprise.context.SessionScoped;  
            import javax.faces.bean.ManagedProperty;
            import javax.faces.bean.NoneScoped;
            import javax.faces.bean.ViewScoped;
             
            @ApplicationScoped
            @RequestScoped
            @SessionScoped
            @ManagedProperty
            @NoneScoped
            @ViewScoped
            public class ApplicationBean2 {
            }              
            """,
            """
            import jakarta.enterprise.context.Dependent;
            import jakarta.faces.annotation.ManagedProperty;
            import jakarta.faces.view.ViewScoped;
  
            import javax.enterprise.context.ApplicationScoped;
            import javax.enterprise.context.RequestScoped;
            import javax.enterprise.context.SessionScoped;
                     
            @ApplicationScoped
            @RequestScoped
            @SessionScoped
            @ManagedProperty
            @Dependent
            @ViewScoped
            public class ApplicationBean2 {
            }             
            """
          )
        );
    }
```
it passsed:
image
I dont have access to push to the branch but with this it should work.

**Comment by timtebeek** [comment]
Thanks for helping review @ranuradh ; I've pushed an update to the test just now!

**Comment by OndroMih** [comment]
Hi, @timtebeek,

I improved your fixes (they weren't testing all imports correctly) and also added a new test for EE 9 to EE 10 migration (Faces 3 to Faces 4).

**Comment by timtebeek** [comment]
Thanks a lot for the detailed fix and extended test @OndroMih ; much appreciated to have both migration paths covered now.

**Pull request merged**
